[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "requests==2.*"
]
build-backend = "setuptools.build_meta"


[too.pytest.ini_options]
addopts = "--cov=nitrado"
testpaths = [
    "tests",
]

[too.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
